// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Restaurant_delivery_online_API.Models
{
    [Table("City")]
    public partial class City
    {
        

        [Key]
        public int CityId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }

        [InverseProperty("City")]
        public virtual ICollection<Restaurant> Restaurants { get; set; }
    }
}