// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Restaurant_delivery_online_API.Models
{
    public partial class MenuItem
    {
        

        [Key]
        public int MenuItemId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal Price { get; set; }
        public int RestaurantId { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Image { get; set; }

        [ForeignKey("RestaurantId")]
        [InverseProperty("MenuItems")]
        public virtual Restaurant Restaurant { get; set; }
        [InverseProperty("MenuItem")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}