// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Restaurant_delivery_online_API.Models
{
    public partial class Order
    {
    

        [Key]
        public int OrderId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime OrderDate { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string CustomerName { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string CustomerPhone { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string CustomerEmail { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string CustomerAddress { get; set; }
        public int RestaurantId { get; set; }

        [ForeignKey("RestaurantId")]
        [InverseProperty("Orders")]
        public virtual Restaurant Restaurant { get; set; }
        [InverseProperty("Order")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}