// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Restaurant_delivery_online_API.Models
{
    [Table("Restaurant")]
    public partial class Restaurant
    {
        

        [Key]
        public int RestaurantId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Image { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Address { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string Phone { get; set; }
        public int CityId { get; set; }

        [ForeignKey("CityId")]
        [InverseProperty("Restaurants")]
        public virtual City City { get; set; }
        [InverseProperty("Restaurant")]
        public virtual ICollection<MenuItem> MenuItems { get; set; }
        [InverseProperty("Restaurant")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}